#!/bin/bash

folder=${1}
host=${2}

if [ $# -eq 2 ]; then
	ssh -4 root@${host} "rm -rf /opt/custom/ && mkdir /opt/custom/"
	scp -4 -r ${folder}/* root@${host}:/opt/custom/
else
	echo "${0} [folder] [host]"
fi
