#!/bin/sh

. /lib/svc/share/smf_include.sh

getproparg() { 
        val=`svcprop -p $1 $SMF_FMRI` 
        [ -n "$val" ] && echo $val 
}

if [ -z "$SMF_FMRI" ]; then 
        echo "SMF framework variables are not initialized." 
        exit $SMF_EXIT_ERR 
fi

OPENVPNBIN='/opt/local/sbin/openvpn'
OPENVPNCONFIG=`getproparg openvpn/config`

if [ -z "$OPENVPNCONFIG" ]; then 
        echo "openvpn/config property not set" 
        exit $SMF_EXIT_ERR_CONFIG 
fi

case "$1" in 
        'start')
                cd `dirname "$OPENVPNCONFIG"`
                $OPENVPNBIN $OPENVPNCONFIG
        ;; 
        'stop') 
                echo "not implemented"
        ;;
        'refresh') 
                echo "not implemented"
        ;;
        *)
                echo $"Usage: $0 {start|refresh}" 
                exit 1 
        ;;
esac

exit $SMF_EXIT_OK
